/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GIU.VendedorCajero;
import GIU.Admi.*;
import javax.swing.JDialog;
import javax.swing.JFrame;
/**
 *
 * @author Aicult'D
 */
public class M_opc_ extends javax.swing.JFrame {

    /**
     * Creates new form M_opc
     */
    public M_opc_() {
        
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Opciones = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        Opciones.setBackground(new java.awt.Color(204, 204, 255));
        Opciones.setPreferredSize(new java.awt.Dimension(262, 660));
        Opciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu20x20.png"))); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(36, 36));
        Opciones.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, -1, -1));

        jLabel1.setDisplayedMnemonic('4');
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/usuario160x160.png"))); // NOI18N
        Opciones.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/G_Usuario 20x20.png"))); // NOI18N
        jLabel2.setText("Flujo Caja");
        jLabel2.setToolTipText("");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setMaximumSize(new java.awt.Dimension(43, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(43, 20));
        jLabel2.setName(""); // NOI18N
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(176, 43));
        Opciones.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 271, 250, 38));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/G_Cliente 20x20.png"))); // NOI18N
        jLabel4.setText("Apertura caja");
        jLabel4.setMaximumSize(new java.awt.Dimension(43, 20));
        jLabel4.setMinimumSize(new java.awt.Dimension(43, 20));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(176, 43));
        Opciones.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 315, 250, 38));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/G_Sedes 20x20.png"))); // NOI18N
        jLabel5.setText("Realizar cierre de caja");
        jLabel5.setMaximumSize(new java.awt.Dimension(43, 20));
        jLabel5.setMinimumSize(new java.awt.Dimension(43, 20));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(176, 43));
        Opciones.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 359, 250, 38));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/G_Proveedores 20x20.png"))); // NOI18N
        jLabel6.setText("Crear nueva venta");
        jLabel6.setMaximumSize(new java.awt.Dimension(43, 20));
        jLabel6.setMinimumSize(new java.awt.Dimension(43, 20));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(176, 43));
        Opciones.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 403, 250, 38));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/G_Productos 20x20.png"))); // NOI18N
        jLabel7.setText("Consultar venta");
        jLabel7.setMaximumSize(new java.awt.Dimension(43, 20));
        jLabel7.setMinimumSize(new java.awt.Dimension(43, 20));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(176, 43));
        Opciones.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 447, 250, 38));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/C_Abastecimiento 20x20.png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(43, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(43, 20));
        jLabel8.setOpaque(true);
        jLabel8.setPreferredSize(new java.awt.Dimension(176, 43));
        Opciones.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 491, 250, 38));

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/G_Reporte 20x20.png"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(43, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(43, 20));
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(176, 43));
        Opciones.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 535, 250, 38));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Lucía Farfán");
        Opciones.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 228, 240, -1));

        jSeparator3.setForeground(new java.awt.Color(79, 93, 131));
        Opciones.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 262, 250, -1));

        getContentPane().add(Opciones);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(M_opc_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(M_opc_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(M_opc_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(M_opc_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new M_opc_().setVisible(true);
            }
        });
    }
    



    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Opciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
