/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GIU.VendedorCajero;

/**
 *
 * @author Eduardo Fernandez
 */
public class vendedor_menu_pop_2 extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public vendedor_menu_pop_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Opciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        Opciones.setBackground(new java.awt.Color(17, 141, 192));
        Opciones.setMinimumSize(new java.awt.Dimension(262, 660));
        Opciones.setPreferredSize(new java.awt.Dimension(262, 660));
        Opciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setDisplayedMnemonic('4');
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/usuario160x160.png"))); // NOI18N
        Opciones.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel2.setBackground(new java.awt.Color(17, 141, 192));
        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("        Flujo Caja");
        jLabel2.setToolTipText("");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setMaximumSize(new java.awt.Dimension(43, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(43, 20));
        jLabel2.setName(""); // NOI18N
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(262, 43));
        Opciones.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        jLabel4.setBackground(new java.awt.Color(17, 141, 192));
        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("       Apertura caja");
        jLabel4.setMaximumSize(new java.awt.Dimension(43, 20));
        jLabel4.setMinimumSize(new java.awt.Dimension(43, 20));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(262, 43));
        Opciones.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        jLabel5.setBackground(new java.awt.Color(17, 141, 192));
        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("       Realizar cierre de caja");
        jLabel5.setMaximumSize(new java.awt.Dimension(43, 20));
        jLabel5.setMinimumSize(new java.awt.Dimension(43, 20));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(262, 43));
        Opciones.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        jLabel6.setBackground(new java.awt.Color(17, 141, 192));
        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("        Crear nueva venta");
        jLabel6.setMaximumSize(new java.awt.Dimension(43, 20));
        jLabel6.setMinimumSize(new java.awt.Dimension(43, 20));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(262, 43));
        Opciones.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jLabel7.setBackground(new java.awt.Color(17, 141, 192));
        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("         Consultar venta");
        jLabel7.setMaximumSize(new java.awt.Dimension(43, 20));
        jLabel7.setMinimumSize(new java.awt.Dimension(43, 20));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(262, 43));
        Opciones.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Source Code Pro Black", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Lucía Farfán");
        Opciones.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 250, -1));

        jSeparator3.setForeground(new java.awt.Color(79, 93, 131));
        Opciones.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 262, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Opciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Opciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
